[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gogas1"
name = "BossChallengeMod"
versionNumber = "0.4.2"
description = "Adds resurrection and modifiers to bosses"
websiteUrl = "https://github.com/Gogas1/BossChallengeMod-NineSols"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "1.3.0"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
